// A curated list of common ICD-10 codes for quick selection when recording a
// diagnosis. Not exhaustive — doctors can still enter a custom code and
// description for anything not on this list.
export const COMMON_ICD10_CODES: { code: string; description: string }[] = [
  { code: "J00", description: "Acute nasopharyngitis (common cold)" },
  { code: "J02.9", description: "Acute pharyngitis, unspecified" },
  { code: "J03.90", description: "Acute tonsillitis, unspecified" },
  { code: "J06.9", description: "Acute upper respiratory infection, unspecified" },
  { code: "J18.9", description: "Pneumonia, unspecified organism" },
  { code: "J20.9", description: "Acute bronchitis, unspecified" },
  { code: "J45.909", description: "Asthma, unspecified, uncomplicated" },
  { code: "A09", description: "Infectious gastroenteritis and colitis, unspecified" },
  { code: "K21.9", description: "Gastro-esophageal reflux disease without esophagitis" },
  { code: "K29.70", description: "Gastritis, unspecified, without bleeding" },
  { code: "K59.00", description: "Constipation, unspecified" },
  { code: "N39.0", description: "Urinary tract infection, site not specified" },
  { code: "N30.90", description: "Cystitis, unspecified, without hematuria" },
  { code: "E11.9", description: "Type 2 diabetes mellitus without complications" },
  { code: "E78.5", description: "Hyperlipidemia, unspecified" },
  { code: "I10", description: "Essential (primary) hypertension" },
  { code: "I25.10", description: "Atherosclerotic heart disease" },
  { code: "R51", description: "Headache" },
  { code: "G43.909", description: "Migraine, unspecified, not intractable" },
  { code: "M54.50", description: "Low back pain, unspecified" },
  { code: "M54.2", description: "Cervicalgia (neck pain)" },
  { code: "M25.50", description: "Pain in joint, unspecified" },
  { code: "M79.10", description: "Myalgia, unspecified site" },
  { code: "R05.9", description: "Cough, unspecified" },
  { code: "R50.9", description: "Fever, unspecified" },
  { code: "R10.9", description: "Abdominal pain, unspecified" },
  { code: "R42", description: "Dizziness and giddiness" },
  { code: "R11.0", description: "Nausea" },
  { code: "L20.9", description: "Atopic dermatitis, unspecified" },
  { code: "L30.9", description: "Dermatitis, unspecified" },
  { code: "L23.9", description: "Allergic contact dermatitis, unspecified cause" },
  { code: "J30.9", description: "Allergic rhinitis, unspecified" },
  { code: "H10.9", description: "Conjunctivitis, unspecified" },
  { code: "H66.90", description: "Otitis media, unspecified" },
  { code: "H60.90", description: "Otitis externa, unspecified" },
  { code: "F41.9", description: "Anxiety disorder, unspecified" },
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified" },
  { code: "G47.00", description: "Insomnia, unspecified" },
  { code: "E66.9", description: "Obesity, unspecified" },
  { code: "E03.9", description: "Hypothyroidism, unspecified" },
  { code: "D64.9", description: "Anemia, unspecified" },
  { code: "B34.9", description: "Viral infection, unspecified" },
  { code: "Z00.00", description: "General adult medical examination without abnormal findings" },
  { code: "Z71.3", description: "Dietary counseling and surveillance" },
];
