-- AlterTable
ALTER TABLE "DoctorProfile" ADD COLUMN     "address" TEXT,
ADD COLUMN     "clinicRoom" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dob" TIMESTAMP(3),
ADD COLUMN     "emergencyContact" TEXT,
ADD COLUMN     "gender" "Gender",
ADD COLUMN     "graduationYear" INTEGER,
ADD COLUMN     "languages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "mbbsUniversity" TEXT,
ADD COLUMN     "medicalLicenseNo" TEXT,
ADD COLUMN     "notifyAppointmentCancelled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyLeaveRequestStatus" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyPatientWaiting" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyScheduleReminders" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "nrcNumber" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "professionalBio" TEXT,
ADD COLUMN     "smsOtpEnabled" BOOLEAN NOT NULL DEFAULT false;
